# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(605, 630)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 605, 630))
        self.widget.setObjectName("widget")
        self.ingredients_search = QtWidgets.QScrollArea(self.widget)
        self.ingredients_search.setGeometry(QtCore.QRect(40, 115, 525, 475))
        self.ingredients_search.setWidgetResizable(True)
        self.ingredients_search.setObjectName("ingredients_search")
        self.ingredients_search_contents = QtWidgets.QWidget()
        self.ingredients_search_contents.setGeometry(QtCore.QRect(0, 0, 523, 473))
        self.ingredients_search_contents.setObjectName("ingredients_search_contents")
        self.ingredients_search_grid = QGridLayout(self.ingredients_search_contents)
        self.ingredients_search.setWidget(self.ingredients_search_contents)
        

        self.search_button = QtWidgets.QPushButton(self.widget)
        self.search_button.setGeometry(QtCore.QRect(490, 40, 75, 50))
        self.search_button.setObjectName("search_button")
        self.search_bar = QtWidgets.QLineEdit(self.widget)
        self.search_bar.setGeometry(QtCore.QRect(40, 40, 425, 50))
        self.search_bar.setStyleSheet("font-size: 30px;\n"
"color: black;")
        self.search_bar.setObjectName("search_bar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.search_button.setText(_translate("Dialog", "Search"))
