# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.search_bar.setGeometry(QtCore.QRect(40, 40, 425, 50))
        self.search_bar.setStyleSheet("font-size: 30px;\n"
"color: black;")
        self.search_bar.setObjectName("search_bar")
        self.ingredients_search = QtWidgets.QScrollArea(self.centralwidget)
        self.ingredients_search.setGeometry(QtCore.QRect(40, 115, 525, 475))
        self.ingredients_search.setWidgetResizable(True)
        self.ingredients_search.setObjectName("ingredients_search")
        self.ingredients_search_contents = QtWidgets.QWidget()
        self.ingredients_search_contents.setGeometry(QtCore.QRect(0, 0, 523, 473))
        self.ingredients_search_contents.setObjectName("ingredients_search_contents")
        self.ingredients_search.setWidget(self.ingredients_search_contents)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(490, 40, 75, 50))
        self.search_button.setObjectName("search_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_button.setText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
